version: "3"
services:
  postgres:
    container_name: postgres_kona
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
    env_file:
      - docker.env
    networks:
      - postgres

volumes:
  postgres:

networks:
  postgres:
    driver: bridge
